### ISSUE TITLE
SIPExtraction error

### ISSUE THREAD

**Issue by mezeijozsef** [eark-project/earkweb#27]
After creating a SIP, on it's active page we cannot continue the SIP to AIP tasks with SIPExtraction because there is an error:

Task cannot be executed at the current task state (last executed task: SIPtoAIPReset, input accepted from previous tasks: ['IdentifierAssignment'])

**Comment by shsdev** [comment]
Do you still have this error? If the task order is correct, this should actually not happen.

**Comment by mezeijozsef** [comment]
There is no issue anymore with this step.
