### ISSUE TITLE
AIP package search / Package file search not working

### ISSUE THREAD

**Issue by mezeijozsef** [eark-project/earkweb#29]
AIP package search and Package file search seems to be not working at all. 
After running the search, even if E-ARK WEB is empty, shouldn't it say, no search result, giving a feedback that the search was completed?

**Comment by shsdev** [comment]
In the large scale installation, the package file search is not available. This option is actually for the lightweight version and will be deactivated in your installation. However, if this feature is desired, an additonal SolR instance can be made available to provide this feature.

**Comment by mezeijozsef** [comment]
What kind of search will be available then? I cannot see other search module now.

**Comment by shsdev** [comment]
In principle the local storage AIP indexing is for the leightewight version. It requires another instance of SolR running on the server which is not installed on your server. If you enable both, you would have two different search servers. Would you like to enable both? Then we would have to install another SolR instance on the master.

**Comment by mezeijozsef** [comment]
Yes, please! Install the other Solr service on the master.

**Comment by shsdev** [comment]
Can we close this issue? The SolR service for the local storage is installed in the pilot.
