### ISSUE TITLE
Search results 404

### ISSUE THREAD

**Issue by mezeijozsef** [eark-project/earkweb#33]
The files we uploaded inside the SIPs can not be opened.
Search results seems fine, but after listing the found files, those can not be opened (except the files from the schemas folder)

![Uploading earkweb-100-ip.JPG…]()

**Comment by mezeijozsef** [comment]
![earkweb-100-ip](https://cloud.githubusercontent.com/assets/19432723/16910633/0c072a5e-4cda-11e6-967a-946efe15c6cc.JPG)

**Comment by shsdev** [comment]
Is this issue solved by the corrections we made in the pilot installation in July?

**Comment by mezeijozsef** [comment]
Yes thank you!
