### ISSUE TITLE
Uploading SIP - ascii character code

### ISSUE THREAD

**Issue by mezeijozsef** [eark-project/earkweb#34]
The SIP's file name cannot have special characters, because uploading them to E-ARK WEB cause an error.

RODA-in offers different naming method when we export SIPs, like: title + id, or id + date.. etc. We could save our SIPs made with RODA-in with their unique ID, but that way would be hardly recognizable.

![ascii-earkweberror](https://cloud.githubusercontent.com/assets/19432723/17292809/7af6e568-57ec-11e6-839f-a659e73eed42.JPG)

**Comment by shsdev** [comment]
Already solved in 0.9.1, a related issue (file view by double click on file item in working area is solved by commit https://github.com/eark-project/earkweb/commit/6fade81c484dac92da15a2492e16caba1a243d0b which will become available in release 0.9.2)
