### ISSUE TITLE
SIP Creator - upload of files but not folders  

### ISSUE THREAD

**Issue by PhillipTommerholt** [eark-project/earkweb#36]
According to the SIARD2.0 format you can have external LOBs in folders outside the SIARD file.
When I use the "Create SIP"-function I can only upload files - not folders:

![udklip](https://cloud.githubusercontent.com/assets/15984159/17620632/f7695a3c-608d-11e6-81cb-1793020150e8.PNG)

**Comment by janrn** [comment]
This does not work for the same reason as #37 , but you should be able to do it manually as well.

**Comment by shsdev** [comment]
You can create a TAR package which will be automatically unpackaged when it is uploaded. That's how I do this always in our test installation.

Generally, if you would like to upload a complete folder, you would have to package it before. We could extend this functionality to expanding ZIP files automatically if this is better supported on your work stations. Just let me know if you need it.
