### ISSUE TITLE
SIP creator Premis 3.0

### ISSUE THREAD

**Issue by PhillipTommerholt** [eark-project/earkweb#38]
When creating a SIP it looks like earkweb places a Premis 2.2 schema.

![uadklip](https://cloud.githubusercontent.com/assets/15984159/17620869/bc241532-608f-11e6-878e-c18132a2b1d3.PNG)

I guess this should be a Premis 3.0. 

_The current AIP spec does use 2.2 but the SIP spec and DIP spec uses 3.0. I believe it has been decided that the AIP spec will amend to 3.0 too_

**Comment by shsdev** [comment]
That's true. The reference installation still uses PREMIS version 2.2. One of the tasks in our pipeline is to update to PREMIS 3.0.

**Comment by shsdev** [comment]
PREMIS 3.0 is now used
