### ISSUE TITLE
Packages names (AIP to DIP conversion) must be unique

### ISSUE THREAD

**Issue by andreaskring** [eark-project/earkweb#39]
When posting orders from the OMT, the submitted "order_title" must be unique. Otherwise the following JSON is returned:
`{
  "message": "IntegrityError(1062, \"Duplicate entry 'Flour1' for key 'PRIMARY'\")",
  "success": false
}`
This could be a problem since different users of the OMT may use the same order title.

It is possible to change this, or should I add some UUID like string to the order title before sending it from the OMT?
(this will lead to some not so pretty packages names in earkweb)

**Comment by bartham** [comment]
The name is used as primary key in a table and also referenced in other places. So in short due to the current information model it is difficult to change at this point.

**Comment by andreaskring** [comment]
Ok - I will add an UUID to the order title
