### ISSUE TITLE
Cannot post order with the same title as a previously deleted order

### ISSUE THREAD

**Issue by andreaskring** [eark-project/earkweb#40]
(this issue is related to #39 )

Here is what I did:
Submitting an order from the OMT by sending this JSON `{'order_title': u'Flour2', 'aip_identifiers': ['urn:uuid:adb2b78e-c9c2-a35a-8cfa-f163612b3a08']}`. This works fine, and I can see the order in list of active AIP to DIP creation processes (there is a typo in the page displaying this list - it says "Active SIP to AIP conversion processes" and not "Active AIP to DIP conversion processes"). If I delete the IP by using the "IPdelete" task the process succeeds fine and the process is removed from the list. However, when I try to submit the order again, i.e. sending the same JOSN as above, I get the response `{
  "message": "IntegrityError(1062, \"Duplicate entry 'Flour2' for key 'PRIMARY'\")",
  "success": false
}`, so it seems as if the process/package was not deleted properly?

**Comment by shsdev** [comment]
No integration with order management tool.
