### ISSUE TITLE
tar file from DIP storage cannot be unpacked

### ISSUE THREAD

**Issue by andreaskring** [eark-project/earkweb#42]
In the AIP to DIP conversion workflow, I completed the task "DIPStore" (with status "succes") and the DIP is stored in `/var/data/earkweb/storage/pairtree_root/69/b8/19/c7/-f/29/d-/45/0b/-a/94/e-/56/88/e5/9c/ef/65/data/00001/69b819c7-f29d-450b-a94e-5688e59cef65.tar`

When I try to unpack this tar-file, I get this error:

```
$ tar xvf 69b819c7-f29d-450b-a94e-5688e59cef65.tar
69b819c7-f29d-450b-a94e-5688e59cef65/metadata/earkweb.log
69b819c7-f29d-450b-a94e-5688e59cef65/metadata/preservation/premis.xml
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

**Comment by bartham** [comment]
Can you reproduce this or is a one time thing. EOF can occur for many reasons like filesystem corruption, full filesystem, interrupted celery task and so on

**Comment by andreaskring** [comment]
Yes - it can be reproduced. I have just tried it again with another package and I got the same error.

**Comment by andreaskring** [comment]
@bartham Have you tested this - and if so: do you also experience the same problem?

**Comment by andreaskring** [comment]
@bartham It is still not working.

On my local VM I did the following:
1) Ran the script /home/eark/git-update-earkweb.sh
2) Ran $ sudo service earkweb stop
3) Ran $ sudo service earkweb start
4) Submitted a new order from the OMT
5) Ran through the AIP to DIP conversion tasks (last one was DIPStorage)
6) Tried to untar the DIP

The last step above gave the same error as previously

**Comment by bartham** [comment]
Hi,

You should get an exception of some sort. Please look in the logs and send me the details.
If you do curl you should get at least an exception upon DIPPackaging.

Cheers,
Mihai

**Comment by bartham** [comment]
I think I know what’s wrong.
Please restart celery.

Let me know if it helped.
Mihai

**Comment by andreaskring** [comment]
@bartham I also tried restarting Celery, but I still get the same error, i.e. I tried

$ sudo service celeryd restart

**Comment by bartham** [comment]
Can we do a teamviewer meeting or skype to see what you are doing.

Cheers,

**Comment by andreaskring** [comment]
@bartham Sure - thanks. I will try to reach you on Skype now

**Comment by shsdev** [comment]
Solved offline.
