### ISSUE TITLE
AIP to DIP: DIPAcquireAIPs cannot be run as the first task

### ISSUE THREAD

**Issue by andreaskring** [eark-project/earkweb#43]
After submitting an order from the OMT to earkweb, I can see the newly created AIP to DIP conversion process in the list of active AIP to DIP conversion processes. In this list I can see that "Last task" has the value AIPtoDIPReset and "Process status" has the value Success.

However, when I click on the process and then run the task "DIPAcquireAIPs", I get an error?

Output from process log:

```
Task execution: DIPAcquireAIPs task 74dd4bdd-f472-4e30-ae10-c50b5263996e
Processing package 5f7fabe2-2410-4ee9-af38-b6919ecd1bf1
```

Output from error log:

```
Task execution request rejected ('package task_status=-1')
Task status is undefined (-1). Task status must be set in task implementation.
```

If I first run the task AIPtoDIPReset and then run DIPAcquireAIPs things are working fine, but I guess that it should not be necessary to run AIPtoDIPReset first?

**Comment by shsdev** [comment]
Obsolete with new task execution setup.
