### ISSUE TITLE
Value of "Last task" in AIP to DIP conversion does not change

### ISSUE THREAD

**Issue by andreaskring** [eark-project/earkweb#45]
When I make call a like this
```
$ curl -X POST -d '{"process_id": "c1b1c16e-2c00-474f-b99b-42019b3eaeed"}' http://localhost:8000/earkweb/search/prepareDIPWorkingArea
```
and get a 201 response back, the "Last task" for this process is still AIPtoDIPReset in earkweb, but should this not be DIPExtractAIPs?

**Comment by bartham** [comment]
Hi,

Well it seems that the status is not written to the DB. I’ll have to talk to Sven about it. But if you are In Oslo you can ask him yourself.
I’ll see maybe I find a quick fix.

Cheers,
Mihai

**Comment by andreaskring** [comment]
The same problem occurs after sending a request to:
```
POST /earkweb/createDIP
```

**Comment by shsdev** [comment]
The status of the process is currently not updated in the db.

**Comment by shsdev** [comment]
Obsolete with new task execution setup.
