### ISSUE TITLE
EAD parsing error (SIP creation)

### ISSUE THREAD

**Issue by PhillipTommerholt** [eark-project/earkweb#46]
![image](https://cloud.githubusercontent.com/assets/15984159/22199955/590b9066-e15d-11e6-8a52-b64d32309e6f.png)

In Altova XMLspy I can validate without errors.

**Comment by shsdev** [comment]
This is due to an issue related to the XMLSchema which is being discussed here:

https://github.com/SAA-SDT/EAD3/issues/499

In the meantime, you can comment out line 1407 in the EAD Schema as follows:

```
<xs:complexType name="e.anyname">
    <xs:choice>
      <xs:any namespace="##other" processContents="lax"/>
      <!--xs:any namespace="##local" processContents="lax"/-->
    </xs:choice>
</xs:complexType>
```
