### ISSUE TITLE
API for manual entry of PREMIS events

### ISSUE THREAD

**Issue by GregorARS** [eark-project/earkweb#47]
In the archival process of preparing a DIPu there are scenarios in which some manual preparation of materials is needed (like converting geodata from one coordinate system to another, or using ). And this kind of actions call for manual PREMIS entries. 
So I propose you create an API in which you can enter an entry into PREMIS manualy within the DIPu preparation process.

**Comment by shsdev** [comment]
API function added with commit 1919d9850f09678cf74267f7a03592ad13414724

Documentation added in the developer notes:

https://github.com/eark-project/earkweb/blob/master/docs/developer_notes.md#add-premis-event
