### ISSUE TITLE
Fatal error running docker compose build

### ISSUE THREAD

**Issue by luis100** [eark-project/earkweb#48]
Using the code in master branch as of commit e779e38f87349f41dc074908ec5ba12fa9b3f002

Followed docker instructions, using docker compose script, got a fatal error loading a SIP.

Console output: [eark_docker_compose.log.zip](https://github.com/eark-project/earkweb/files/961465/eark_docker_compose.log.zip)

Used SIP (created with RODA): [digitally signed text .zip](https://github.com/eark-project/earkweb/files/961466/digitally.signed.text.zip)

Note that on startup it console already shows an error about the missing table. 

```
django.db.utils.ProgrammingError: (1146, "Table 'eark.workflow_workflowmodules' doesn't exist")
```

![programmingerror at -earkweb-sip2aip-upload_sip_delivery](https://cloud.githubusercontent.com/assets/631728/25482191/798af98c-2b48-11e7-93b7-ab1441ba55ae.jpg)

**Comment by shsdev** [comment]
docker-compose updated
