### ISSUE TITLE
Lily 2.4 binary installation didn't available 

### ISSUE THREAD

**Issue by kristonova** [eark-project/earkweb#49]
I just implemented the EARK backend for my undergraduate thesis. But I got stuck at installing Lily. I downloaded Lily at http://www.lilyproject.org/lily/downloads.html but the web page said that Lily 2.4 binary installation didn't available again. Could you give me a Lily 2.4 binary installation file? I can be contacted via my email krisostomus.nova.r@mail.ugm.ac.id. Any helps are really appreciated!

**Comment by shsdev** [comment]
In E-ARK, Lily was used as a repository that provides fast access to archived content. The purpose was to store AIPs in archival storage (e.g. tape storage) and at the same time store the content using the lily repository. As lily provides full text indexing and access to records based on REST interfaces, it allows users and archivists to quickly search and access the archived content. 
In the meantime, the Lily project is is no longer maintained and relies on an outdated Hadoop version. A port to a CDH5.8 based on Cloudera search is therefore required.
