### ISSUE TITLE
Db issue - fatal error (docker installation) and ghostcript missing link 

### ISSUE THREAD

**Issue by saponidas** [eark-project/earkweb#50]
The installation using docker and docker compose result in some issue with the database when creating a new SIP or Stating a new AIP.  There are missing tables in the eark db
It seems the same issue that report @luis100 a year ago
https://github.com/eark-project/earkweb/issues/48

**Error creating a new SIP**
> Request

 Method: | GET
-- | --
http://ip:8000/earkweb/sipcreator/
1.9
ProgrammingError
(1146, "Table 'eark.workflow_workflowmodules' doesn't exist")
/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py in defaulterrorhandler, line 36
/usr/bin/python
2.7.6
['/earkweb',  '/usr/lib/python2.7/dist-packages',  '/usr/local/lib/python2.7/dist-packages/fido-1.3.0-py2.7.egg',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/earkweb',  '/opt/python_wsgi_apps/earkweb']
Wed, 5 Dec 2018 11:00:22 +0100

These are the existing tables;
| Tables_in_eark              |
+-----------------------------+
| auth_group                  |
| auth_group_permissions      |
| auth_permission             |
| auth_user                   |
| auth_user_groups            |
| auth_user_user_permissions  |
| celery_taskmeta             |
| celery_tasksetmeta          |
| django_admin_log            |
| django_content_type         |
| django_migrations           |
| django_session              |
| djcelery_crontabschedule    |
| djcelery_intervalschedule   |
| djcelery_periodictask       |
| djcelery_periodictasks      |
| djcelery_taskstate          |
| djcelery_workerstate        |
| earkcore_informationpackage |
+-----------------------------+
19 rows in set (0.00 sec)

And , **if you try build images and run as individual containers**, when build earkweb image it crash in steP 17 ghostcript because the release 9.18 link has been moved:
https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/tag/gs918

Tested in Ubuntu 14.04 and 16.04.

These issue make earkweb unable to install. Can you take a look.

Regards,

**Comment by saponidas** [comment]
Any update for this?
@shsdev @luis100 @rschmidt13 @DarkStar1 

Regards,

**Comment by shsdev** [comment]
This project will be restructured completely. In the course of the next months the project will be updated. Instead of a multi-container docker setup, there will be a single container for testing the application.

**Comment by shsdev** [comment]
Update of the earkweb instance is planned to happen in the first three months of 2020.

**Comment by shsdev** [comment]
ghostscript and docker setup updated
