### ISSUE TITLE
Docker installation - missing language files

### ISSUE THREAD

**Issue by rgraf** [eark-project/earkweb#55]
By docker deployment may happen that some language files are missing. In particular "django.mo". This results in some missing important menu items, such as "Information package creation". To fix this either is required to follow documentation here: https://github.com/E-ARK-Software/earkweb/blob/master/docs/install_manual.md or copy these files to related location before "docker-compose build" (e.g. earkweb/locale/en/LC_MESSAGES for english language).

**Comment by shsdev** [comment]
This is fixed in the current version
