### ISSUE TITLE
Celery is not started automatically from docker

### ISSUE THREAD

**Issue by rgraf** [eark-project/earkweb#60]
This can be checked in dashboard: http://localhost:8000/earkweb/administration/dashboard Sometimes Celery does not start automatically from docker deployment. This can be fixed, when you start it manually from inside earkweb1 running docker container:

in one terminal:
root@2eb1e1400ec7:/earkweb# cat run_all.sh 
#!/bin/bash
sleep 20
echo "Starting celery ..."
# cd /earkweb && celery multi start ingestqueue -A earkweb.celery --concurrency=4 -Ofair --pidfile=/data/celery_worker.pid  --logfile=/data/celery_default_queue.log
# cd /earkweb && celery -A earkweb.celery worker --pool threads -Ofair --pidfile=/data/celery_worker.pid  --logfile=/data/celery_default_queue.log &
cd /earkweb && celery -A earkweb.celery worker --pool prefork -Ofair --pidfile=/var/data/celery_worker.pid  --logfile=/var/data/celery_default_queue.log &
sleep 3
echo "Starting flower ..."
cd /earkweb && celery -A earkweb.celery flower --port=5555 >/var/data/flower.log 2>&1 &
sleep 3
echo "Starting earkweb ..."
cd /earkweb && python3 manage.py runserver 0.0.0.0:8000
root@2eb1e1400ec7:/earkweb# celery -A earkweb.celery worker --pool prefork -Ofair

in the second terminal:
root@osboxes:/home/osboxes# docker exec -it earkweb1 /bin/bash
root@2eb1e1400ec7:/# cd earkweb
root@2eb1e1400ec7:/earkweb# celery -A earkweb.celery status

**Comment by bartham** [comment]
Celery starts successfully. Problem was running docker in sandbox via snap. Deployed on test server.

**Comment by shsdev** [comment]
This is fixed in the current version
