### ISSUE TITLE
Broken package by creation using API methods

### ISSUE THREAD

**Issue by rgraf** [eark-project/earkweb#61]
It is possible to create a package with manipulated package id e.g. "string". For example:
  {
    "process_id": "string",
    "work_dir": "string",
    "package_name": "99",
    "external_id": "string",
    "identifier": "string",
    "version": 0,
    "storage_dir": "string",
    "last_change": "2020-08-06T19:19:15.178662+02:00"
  }
Later it is not possible to find it and to remove this package using GET and DELETE methods "/informationpackages/{process_id}/". Error occures: 404 Error: Not Found.

**Comment by shsdev** [comment]
This was fixed in the current version
