### ISSUE TITLE
Duplicated packages with the same package id is possible

### ISSUE THREAD

**Issue by rgraf** [eark-project/earkweb#62]
It is possible to create multiple packages with the same package id e.g. "string". For example:
  {
    "process_id": "string",
    "work_dir": "string",
    "package_name": "99",
    "external_id": "string",
    "identifier": "string",
    "version": 0,
    "storage_dir": "string",
    "last_change": "2020-08-06T19:19:15.178662+02:00"
  },
  {
    "process_id": "string",
    "work_dir": "string",
    "package_name": "88888",
    "external_id": "string",
    "identifier": "string",
    "version": 0,
    "storage_dir": "string",
    "last_change": "2020-08-06T19:22:14.933824+02:00"
  }
using POST method "/informationpackages/".

**Comment by shsdev** [comment]
It is not possible any more to create duplicate packages
