### ISSUE TITLE
Package indexing using API method did not work

### ISSUE THREAD

**Issue by rgraf** [eark-project/earkweb#63]
I've created a package:

  {
    "process_id": "1fdc9763-b586-4f35-ae09-93460021f5a7",
    "work_dir": "/var/data/repo/work/1fdc9763-b586-4f35-ae09-93460021f5a7",
    "package_name": "roman.7",
    "external_id": "doi:10.111/94",
    "identifier": "urn:uuid:4b36751d-7635-48a8-863e-6d943c6c4f70",
    "version": 0,
    "storage_dir": "",
    "last_change": "2020-08-06T19:41:48.355363+02:00"
  }

using POST /informationpackages/

Then I tried to use method POST /storage/informationpackages/{identifier}/index/ for created ID and it was not find for indexing.

**Comment by shsdev** [comment]
Indexing was redesigned, this issue is not present any more
