### ISSUE TITLE
Flower not accessible

### ISSUE THREAD

**Issue by rgraf** [eark-project/earkweb#64]
If we select host system other than Ubuntu 18.04, we have a problem to access flower service.

The celery process is running but cannot be resolved e.g. using curl. And starting of this process manually in earkweb1 container with “–url flower” parameter does not work because original process is running. That is strange. But now after I removed all images and containers and redeployed I can access the dashboard again:

docker exec -it earkweb1 /bin/bash

root@e1a319eeda23:/# celery -A earkweb.celery flower  --url_prefix=flower --port=5555

curl http://localhost:5555/flower -> page not found

root@e1a319eeda23:/earkweb# ps auxf
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          43  0.0  0.1  20536  4088 pts/0    Ss   09:18   0:00 /bin/bash
root         108  0.0  0.0  36072  3360 pts/0    R+   09:37   0:00  \_ ps auxf
root           1  0.0  0.0  20044  3392 ?        Ss   09:11   0:00 /bin/bash /earkweb/run_all.sh /earkweb/run_all.sh
root           7  0.0  0.0  20044   284 ?        S    09:11   0:00 /bin/bash /earkweb/run_all.sh /earkweb/run_all.sh
root           9  0.2  3.4 246724 138880 ?       S    09:11   0:03  \_ /usr/bin/python3 /usr/local/bin/celery -A earkweb.celery worker --pool prefork -Ofair --pidfile=/var/data/celery_worker.pid --logfile=/var/data/celery_default_queue.l
root          25  0.0  3.1 246212 124912 ?       S    09:11   0:00      \_ /usr/bin/python3 /usr/local/bin/celery -A earkweb.celery worker --pool prefork -Ofair --pidfile=/var/data/celery_worker.pid --logfile=/var/data/celery_default_que
root          13  0.0  0.0  20044   284 ?        S    09:11   0:00 /bin/bash /earkweb/run_all.sh /earkweb/run_all.sh
root          15  0.2  3.4 610052 137664 ?       Sl   09:11   0:03  \_ /usr/bin/python3 /usr/local/bin/celery -A earkweb.celery flower --url_prefix=flower --port=5555
root          19  0.0  1.2 128416 50284 ?        S    09:11   0:00 python3 manage.py runserver 0.0.0.0:8000
root          24 11.1  3.4 739788 136052 ?       Sl   09:11   2:53  \_ /usr/bin/python3 manage.py runserver 0.0.0.0:8000

The reason for that seems to be an older version of flower from requirements.txt - 0.9.5

**Comment by shsdev** [comment]
Solved by adding a path to the flower instance.
