### ISSUE TITLE
500 error on demo site (Google Chrome / Edge - Windows)

### ISSUE THREAD

**Issue by ross-spencer** [eark-project/earkweb#70]
Hi there - trying to access the demo site I'm seeing the issue in the screenshots below: 

```console
jquery-1.11.2.js:9659 GET https://earkweb.sydarkivera.se/earkweb/submission/initialize/PACKAGE.NAME.001// 
500 (Internal Server Error)
```

**Screenshots**

_Chrome_

![image](https://user-images.githubusercontent.com/1880412/118978710-e938e980-b977-11eb-9ffe-070ea4f019ad.png)

**NB.** the coloring here is a custom dark reader.

_And in Microsoft Edge:_ 

![image](https://user-images.githubusercontent.com/1880412/118978931-33ba6600-b978-11eb-9d34-6632f6df3da2.png)

**Comment by shsdev** [comment]
This issue is solved in the current version
